openresty:
  images: taomaree/openresty
  environment:
    - TZ=Asia/Shanghai
    - APP_PORT=80
  ports:
    - "80:80/tcp"
    - "443:443/tcp"
  volumes:
    - /srv/data:/srv/data
  restart: always
  privileged: true
